accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', login_check, name='login'),
    path('logout/', logout, name='logout')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('post/', include('post.urls', namespace='post')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from .views import *

app_name = 'post'

urlpatterns = [
    path('', post_list, name='post_list'),
]

accounts/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
import re
# Create your models here.

def user_path(instance, filename):
    from random import choice
    import string
    arr = [choice(string.ascii_letters) for _ in range(8)]
    pid = ''.join(arr)
    extension = filename.split('.')[-1]
    return 'accounts/{}/{}.{}'.format(instance.user.username, pid, extension)
    
class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    nickname = models.CharField('별명', max_length=30, unique=True)
    picture = ProcessedImageField(upload_to=user_path,
                       processors=[ResizeToFill(150,150)],
                       format='JPEG',
                       options={'quality':90},
                       blank=True,
                       )
    about = models.CharField(max_length=300, blank=True)
    
    GENDER_C = (
        ('선택안함', '선택안함'),
        ('여성', '여성'),
        ('남성', '남성'),
    )
    
    gender = models.CharField('성별(선택사항)',
                        max_length=10,
                        choices=GENDER_C,
                        default='N')

post/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from .models import Profile
from django.contrib.auth.models import User


class LoginForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']

class SignupForm(UserCreationForm):
    username = forms.CharField(label='사용자명', widget=forms.TextInput(attrs={
        'pattern' : '[a-zA-Z0-9]+',
        'title' : '특수문자, 공백 입력불가'
    }))
    
    nickname = forms.CharField(label='닉네임')
    picture = forms.ImageField(label='프로필사진', required=False)
    
    class Meta(UserCreationForm.Meta):
        email = UserCreationForm.Meta.fields + ('email',)
    
    def clean_nickname(self):
        nickname = self.cleaned_data.get('nickname')
        if Profile.objects.filter(nickname=nickname).exists():
            raise forms.ValidationError('이미 존재하는 닉네임 입니다')
        return nickname
    
    def clean_email(self):
        email = self.cleaned_data.get('email')
        User = get_user_model()
        if User.objects.filter(email=email).exists():
            raise form.ValidationError('사용중인 이메일 입니다')
        return email
    
    def clean_picture(self):
        picture = self.cleaned_data.get('picture')
        if not picture:
            picture = None
        return picture
    
    def save(self):
        user = super().save()
        Profile.objects.create(
            user=user,
            nickname=self.cleaned_data['nickname'],
            picture =self.cleaned_data['picture'],    
        )
        return user
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

accounts/views.py
from django.shortcuts import render, redirect
from .models import *
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout as django_logout
from .forms import SignupForm, LoginForm

# Create your views here.

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            return redirect('accounts:login')
    else:
        form = SignupForm()
    return render(request, 'accounts/signup.html', {
        'form' : form,
    })


def login_check(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        name = request.POST.get('username')
        pwd = request.POST.get('password')
        
        user = authenticate(username=name,password=pwd)
    
        if user is not None:
            login(request, user)
            return redirect("/")

    else:
        form = LoginForm()
    return render(request, 'accounts/login.html', {
        'form':form
    })

def logout(request):
    django_logout(request)
    return redirect("/")

post/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import get_user_model

# Create your views here.
def post_list(request):
    if request.user.is_authenticated:
        username = request.user
        user = get_object_or_404(get_user_model(), username=username)
        user_profile = user.profile
        return render(request, 'post/post_list.html', {
            'user_profile': user_profile
        })
    else:
        return render(request, 'post/post_list.html')

accounts/templates/accounts/layout.html
{% extends 'layout.html' %}

accounts/templates/accounts/login.html
{% extends 'layout.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}

{% block contents %}
<section id="container">


    <div id="login_section">
        <h1 class="logo"><a href="#" class="icon--main-logo"></a>FACEBOOK</h1>
        <form method = "POST" action="{% url 'accounts:login' %}">
            {% csrf_token %}
            
            <div class="id_section">
                <div><label for="id_username">아이디</label></div>
                <div><input type="text" id="{{ form.username.id_for_label }}" name="{{ form.username.html_name }}"></div>
            </div>

            <div class="pw_section">
                <div><label for="pw_field">비밀번호</label></div>
                <div><input type="password" id="{{form.password.id_for_label}}" name="{{form.password.html_name}}"></div>
            </div>

            <input type="submit" value="SIGN IN" id="submitBtn">

            <div class="signup"><a href="{% url 'accounts:signup' %}">아직도 회원이 아니신가요?</a></div>

        </form>
    </div>


</section>
{% endblock %}

{% block js %}
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'layout.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/signup.css' %}">
{% endblock %}

{% block contents %}
<section id="container">



    <div id="signup_section">
        <h1 class="logo"><a href="#" class="icon--main-logo"></a>회원가입</h1>
        <form action="" method = "post" enctype="multipart/form-data">
            
            {% csrf_token %}
            {{ form.as_p }}
           
            <div class="signup_section">
                <input type="submit" value="SIGN UP" id="submitBtn">
            </div>
            


        </form>
    </div>


</section>
{% endblock %}

{% block js %}
{% endblock %}

config/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="ko-KR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <title>Facebook</title>
    
    <link rel="shortcut icon" href="{% static 'imgs/favicon.png' %}">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/common.css' %}">
    
    {% block head %}
    {% endblock %}
    
</head>
<body>
    <section id="container">
        <header id="header">
            <div class="inner">
                <div class="left">
                    <hl class="icon icon--facebook-white"><a href="#"></a></hl>
                    
                    <div class="search_container">
                        <form action="#">
                            {% csrf_token %}
                            <input type="text" name = "tag" id="search_box" placeholder="검색" required>
                            <button type="submit"><span class="icon--search-black"></span></button>
                        </form>
                    </div>
                    
                </div>
                <div class="right">
                    {% if user_profile %}
                    <div><a href="{% url 'accounts:logout'%}" class="logout">로그아웃</a></div>
                    <div class="my_name"><span class="profile_img"><img src="{{ user_profile.picture.url}}" alt=""></span><a href="#">{{user_profile.nickname}}</a></div>
                    <div class="home"><a href="{% url 'post:post_list' %}">홈</a></div>
                    <div class="people"><a href="#"><span class="icon icon--people-black"></span></a></div>
                    <div class="bell"><span class ="icon icon--bell-black"></span></div>
                    <div><a href="#"><span class="icon icon--messenger--black"></span></a></div>
                    <div><a href="#"><span class="icon icon--chart--black"></span></a></div>
                    <div class="question"><a href="http://www.naver.com"><span class="icon icon--question-black"></span></a></div>
                    
                    {% else %}
                    <div><a href="{% url 'accounts:login'%}" class="login">
로그인</a></div>
                    <div class="my_name"><span class="profile_img"><img src="{% static 'imgs/noun_User.png' %}" alt=""></span><a href="#">{{user_profile.nickname}}</a></div>
                    <div class="home"><a href="{% url 'post:post_list' %}">홈</a></div>
                    <div class="people"><a href="#"><span class="icon icon--people-black"></span></a></div>
                    <div class="bell"><span class ="icon icon--bell-black"></span></div>
                    <div><a href="#"><span class="icon icon--messenger--black"></span></a></div>
                    <div><a href="#"><span class="icon icon--chart--black"></span></a></div>
                    <div class="question"><a href="http://www.naver.com"><span class="icon icon--question-black"></span></a></div>
                    
                    {% endif %}
                </div>
            </div>
        </header>
    {% block contents %}
    {% endblock %}
    
    {% block js %}
    {% endblock %}
    </section>
</body>
</html>

post/templates/post/layout.html
{% extends 'layout.html' %}

post/templates/post/post_list.html
{% extends 'layout.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/main.css' %}">
{% endblock %}

{% block contents %}
<div id = "wrapper">
    <div class="inner">
        <div class="left_box">
            {% if user_profile %}
            <div class="my_name">    
                <div class="profile_img"><img src="{{ user_profile.picture.url}}" alt=""></div>
                <span class="name">{{user_profile.nickname}}</span>
                <span class="icon--more"></span>
            </div>
            <ul class="list">
                <li class="active"><a href="{%url 'post:post_list' %}"><span class="icon icon--news"></span>뉴스피드<span class="icon--more"></span></a></li>
                <li><a href="#"><span class="icon icon--messenger"></span>Messenger <span class="icon--more"></span></a></li>
                <li><a href="#"> <span class="icon icon--save"></span>저장됨 <span class="icon--more"></span></a></li>
                
            </ul>
            {% else %}
            <div class="my_name">    
                <div class="profile_img"><img src="{% static 'imgs/noun_User.png' %}" alt=""></div>
                <span class="name">로그인해주세요</span>
            </div>
            <ul class="list">
                <li class="active"><a href="{%url 'post:post_list' %}"><span class="icon icon--news"></span>뉴스피드<span class="icon--more"></span></a></li>
                <li><a href="#"><span class="icon icon--messenger"></span>Messenger <span class="icon--more"></span></a></li>
                <li><a href="#"> <span class="icon icon--save"></span>저장됨<span class="icon--more"></span></a></li>
            </ul>
            {% endif %}
        </div>
        
        <section id="contents_container">
            <article class="create_box">
            <h2 class="title">게시물만들기</h2>
            <div class="text_field">
                <form id="form_new_post">
                    <input type="hidden" id='csrfmiddlewaretoken' name = 'csrfmiddlewaretoken' value='{{csrf_token}}'>
                    <div class="top">
                        {% if profile_user %}
                        <div class="profile_img"><img src="{{ user_profile.picture.url}}" alt=""></div>
                        {% else %}
                        <div class="profile_img"><img src="{% static 'imgs/noun_User.png' %}" alt=""></div>
                        {% endif %}
                        <p>
                            <textarea name="content" id="text_field" cols="50" rows="5" data-name="add" placeholder="{{user_profile.nickname}}님, 무슨 생각을 하고 계신가요?"></textarea>
                        </p>
                    </div>
                    <div class="middle">
                        <div class="middle">
                            <canvas id="imageCanvas" width="0" height="0"></canvas>
                        </div>
                    </div>
                    <div class="bottom">
                        <input type="file" name="photo" id="id_photo" required>
                        
                        <div class="import-btn">
                            <label for="id_photo" id="photo_label"><span class="icon icon--picture"></span>사진/동영상</label>
                        </div>
                    </div>
                    <div class="submit">
                        <input type="button" id="submitBtn" value="게시" disabled>
                    </div>
                </form>
                
            </div>
            </article>
            <div class="contents_wrapper"></div>    
        </section>
        <div class="right_box">
            <header class="title">내 프로필</header>
            {% if user_profile %}
            <div class="right_profile">
                <div class="profile_img"><img src="{{ user_profile.profile.picture.url}}". alt=""></div>
                <div class="detail">
                    <div class="name"><a href="#">{{user_profile.user.profile.nickname}}</a></div>
                    <div class="message"><span class="icon icon--write-gray"></span>메세지</div>
                    
                </div>
            </div>
            {% else %}
            <div class="right_profile">
                <div class="profile_img"><img src="{% static 'imgs/noun_User.png' %}" alt=""></div>
                <div class="detail">
                    <div class="name"><a href="#">로그인해주세요</a></div>
                    <div class="message"><span class="icon icon--write-gray"></span>메세지</div>
                    
                </div>
            </div>            
            {% endif %}
        </div>
    
    </div>
</div>
<div id = "side_box">
    <ul>
        <li>
            <div class="profile_img"><img src="{% static 'imgs/noun_User.png' %}" alt=""></div>
            <div class="name">카인드패밀리</div>
            <div class="light"></div>
        </li>
    </ul>
</div>
{% endblock %}

{% block js %}
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="{% static 'js/main.js' %}"></script>
<script src="{% static 'js/new_post.js' %}"></script>
{% endblock %}